### ISSUE TITLE
linker exited with status 1

### ISSUE THREAD

**Issue by axelvf** [CyberShadow/turbotuber#1]
Im trying to build the project and fails in linking step:

Linking...
/usr/bin/dmd -of.dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber .dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber.o ../.dub/packages/crypto-0.2.16/crypto/.dub/build/library-release-linux.posix-x86_64-dmd_v2.098.0-09C409721F0E49C8D73116E5B2BA1716/libcrypto.a ../.dub/packages/intel-intrinsics-1.6.0/intel-intrinsics/.dub/build/library-release-linux.posix-x86_64-dmd_v2.098.0-9EB55B301F8C19DD402FCE1D6379E144/libintel-intrinsics.a -L--no-as-needed -L-lssl -L-lcrypto -L-lz
.dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber.o: In function `_D2ae3net3ssl7openssl16SSL_library_initFZv':
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl16SSL_library_initFZv[_D2ae3net3ssl7openssl16SSL_library_initFZv]+0x9): undefined reference to `OPENSSL_init_ssl'
.dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber.o: In function `_D2ae3net3ssl7openssl26OpenSSL_add_all_algorithmsFZv':
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl26OpenSSL_add_all_algorithmsFZv[_D2ae3net3ssl7openssl26OpenSSL_add_all_algorithmsFZv]+0x9): undefined reference to `OPENSSL_init_ssl'
.dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber.o: In function `_D2ae3net3ssl7openssl25_sharedStaticCtor_L136_C1FZv':
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl25_sharedStaticCtor_L136_C1FZv[_D2ae3net3ssl7openssl25_sharedStaticCtor_L136_C1FZv]+0x9): undefined reference to `OPENSSL_init_ssl'
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl25_sharedStaticCtor_L136_C1FZv[_D2ae3net3ssl7openssl25_sharedStaticCtor_L136_C1FZv]+0x12): undefined reference to `OPENSSL_init_ssl'
.dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber.o: In function `_D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv':
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv[_D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv]+0x49): undefined reference to `BN_get_rfc3526_prime_1536'
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv[_D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv]+0x52): undefined reference to `BN_get_rfc3526_prime_2048'
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv[_D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv]+0x5b): undefined reference to `BN_get_rfc3526_prime_3072'
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv[_D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv]+0x64): undefined reference to `BN_get_rfc3526_prime_4096'
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv[_D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv]+0x6d): undefined reference to `BN_get_rfc3526_prime_6144'
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv[_D2ae3net3ssl7openssl14OpenSSLContext8enableDHMFiZv]+0x76): undefined reference to `BN_get_rfc3526_prime_8192'
.dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber.o: In function `_D2ae3net3ssl7openssl14OpenSSLContext8setFlagsMFiZv':
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLContext8setFlagsMFiZv[_D2ae3net3ssl7openssl14OpenSSLContext8setFlagsMFiZv]+0x1c): undefined reference to `SSL_CTX_set_options'
.dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber.o: In function `_D2ae3net3ssl7openssl14OpenSSLAdapter10disconnectMFAyaEQCbQCb8asockets14DisconnectTypeZv':
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLAdapter10disconnectMFAyaEQCbQCb8asockets14DisconnectTypeZv[_D2ae3net3ssl7openssl14OpenSSLAdapter10disconnectMFAyaEQCbQCb8asockets14DisconnectTypeZv]+0x1f): undefined reference to `SSL_in_init'
.dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber.o: In function `_D2ae3net3ssl7openssl14OpenSSLAdapter10initializeMFZv':
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLAdapter10initializeMFZv[_D2ae3net3ssl7openssl14OpenSSLAdapter10initializeMFZv]+0x9e): undefined reference to `SSL_set_hostflags'
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLAdapter10initializeMFZv[_D2ae3net3ssl7openssl14OpenSSLAdapter10initializeMFZv]+0xab): undefined reference to `SSL_set1_host'
.dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/turbotuber.o: In function `_D2ae3net3ssl7openssl14OpenSSLAdapter11updateStateMFZv':
../.dub/packages/ae-0.0.3100/ae/net/ssl/openssl.d:(.text._D2ae3net3ssl7openssl14OpenSSLAdapter11updateStateMFZv[_D2ae3net3ssl7openssl14OpenSSLAdapter11updateStateMFZv]+0x350): undefined reference to `SSL_is_init_finished'
collect2: error: ld returned 1 exit status
Error: linker exited with status 1
FAIL .dub/build/application-release-linux.posix-x86_64-dmd_v2.098.0-4B11C57C4FD3B8CE0B106D355B839078/ turbotuber executable
/usr/bin/dmd failed with exit code 1.

**Comment by CyberShadow** [comment]
What OS / distro and version are you on, please

**Comment by axelvf** [comment]
Ubuntu Release:	16.04
Codename:	xenial

**Comment by CyberShadow** [comment]
16.04 is EOL, you probably should update.

In any case that distribution still has OpenSSL 1.0 (which is before the ABI breakage at 1.1).

You could try:

```
$ dub build --override-config=ae:openssl/lib-implicit-1.0
```

**Comment by axelvf** [comment]
Same error but I'll try building using Docker with the latest version. News soon. Thank you!

**Comment by eatkd** [comment]
I am having the same issue while making build (I have windows 10)
$ dub
Performing "debug" build using C:\Program Files\Dlang\D\dmd2\windows\bin\dmd.exe for x86_64.
turbotuber ~master: building configuration "application"...
turbotuber.d(463,4): Error: undefined identifier `ftruncate`
C:\Program Files\Dlang\D\dmd2\windows\bin\dmd.exe failed with exit code 1.



$ dub build -b release
Performing "release" build using C:\Program Files\Dlang\D\dmd2\windows\bin\dmd.exe for x86_64.
turbotuber ~master: building configuration "application"...
turbotuber.d(463,4): Error: undefined identifier `ftruncate`
C:\Program Files\Dlang\D\dmd2\windows\bin\dmd.exe failed with exit code 1.

**Comment by CyberShadow** [comment]
Oh, so Windows doesn't have `ftruncate`...

**Comment by CyberShadow** [comment]
> I am having the same issue while making build (I have windows 10)

No, not the same issue.

**Comment by eatkd** [comment]
> Oh, so Windows doesn't have `ftruncate`...

how can I fix this?

**Comment by CyberShadow** [comment]
Try this patch (I don't have Windows):

```diff
diff --git a/turbotuber.d b/turbotuber.d
index 70140b3..0a51c0f 100644
--- a/turbotuber.d
+++ b/turbotuber.d
@@ -1,4 +1,3 @@
-import core.sys.posix.unistd;
 import core.time;
 
 import std.algorithm.comparison;
@@ -460,8 +459,11 @@ private:
 		{
 			import std.stdio : File;
 			auto f = File(outputFileName, "wb");
-			ftruncate(f.fileno, totalSize);
+			f.seek(totalSize - 1);
+			ubyte z;
+			f.write((&z)[0..1]);
 			f.close();
+
 			fileData = mapFile(outputFileName, MmMode.readWrite, 0, totalSize);
 		}
 		if (fileData && totalSize != unknown)
```

**Comment by eatkd** [comment]
@CyberShadow doing this gave me this error
$ dub build -b release
Performing "release" build using C:\Program Files\Dlang\D\dmd2\windows\bin\dmd.exe for x86_64.
turbotuber ~master: building configuration "application"...
Linking...
lld-link: error: could not open 'ssl.lib': no such file or directory
lld-link: error: could not open 'crypto.lib': no such file or directory
Error: linker exited with status 1
C:\Program Files\Dlang\D\dmd2\windows\bin\dmd.exe failed with exit code 1.

**Comment by CyberShadow** [comment]
Yes, you need OpenSSL.

**Comment by axelvf** [comment]
@CyberShadow For easy debug, I just created a Dockerfile using the Ubuntu latest version ☺️ :
https://gist.github.com/axelvf/e9a44f9f22ba89a49c3ccb08e7f5664e
It builds into /app/turbotuber folder

Trying to download over turbotuber got the same network limitations:
youtube-dl --external-downloader "/root/turbotuber/aria2c" "https://www.youtube.com/watch?v=UN1p4zfAwJg" --output "./%(id)s.%(ext)s" -f 18 
[youtube] UN1p4zfAwJg: Downloading webpage
[download] Destination: ./UN1p4zfAwJg.mp4
[download]   6.4% of 13.46MiB at 74.83KiB/s ETA 02:52

**Comment by eatkd** [comment]
> Yes, you need OpenSSL.

How do I get openssl for D for windows 10 ? when I do
$dub add openssl

Failed to get versions for package openssl on provider registry at https://code.dlang.org/ (fallbacks registry at https://codemirror.dlang.org/, registry at https://dub.bytecraft.nl/, registry at https://code-mirror.dlang.io/): Failed to download https://code.dlang.org/api/packages/infos?packages=%5B%22openssl%22%5D&include_dependencies=true&minimize=true
Could not find package 'openssl'.

I get this error

**Comment by CyberShadow** [comment]
Dub will automatically install the D bindings, so you just need the OpenSSL .lib files (not D specific).

I'm not sure because I haven't done Windows builds in a long time but I think these builds may work:
https://slproweb.com/products/Win32OpenSSL.html

**Comment by axelvf** [comment]
> @CyberShadow For easy debug, I just created a Dockerfile using the Ubuntu latest version ☺️ : https://gist.github.com/axelvf/e9a44f9f22ba89a49c3ccb08e7f5664e It builds into /app/turbotuber folder
> 
> Trying to download over turbotuber got the same network limitations: youtube-dl --external-downloader "/root/turbotuber/aria2c" "https://www.youtube.com/watch?v=UN1p4zfAwJg" --output "./%(id)s.%(ext)s" -f 18 [youtube] UN1p4zfAwJg: Downloading webpage [download] Destination: ./UN1p4zfAwJg.mp4 [download] 6.4% of 13.46MiB at 74.83KiB/s ETA 02:52

@CyberShadow Now its working after install aria2c using (apt-get install aria2).
Testing using proxy not work and the output fails if its different to . (example /tmp because always saves the .part in .)
If you need more info let me know

**Comment by CyberShadow** [comment]
> @CyberShadow Now its working after install aria2c using (apt-get install aria2).

Not sure how that's related, might be just random.

> Testing using proxy not work

Yeah, you need a proxifier like redsocks or maybe proxychains for turbotuber, it doesn't have native proxy support.

> and the output fails if its different to . (example /tmp because always saves the .part in .)

No idea what this could be as it doesn't do any path manipulation, might be something with youtube-dl.
